export const Footer = () => {
  return (
    <footer className="border-t border-border bg-card mt-16">
      <div className="container mx-auto px-4 py-6">
        <p className="text-xs text-muted-foreground leading-relaxed">
          Disclaimer: TermsLens is an AI-powered tool intended for informational and educational purposes only. 
          The analysis provided is generated by large language models (LLMs) and is not a substitute for professional legal advice. 
          The output may contain errors, inaccuracies, or omissions, and has not been reviewed by a qualified attorney. 
          Your use of this tool does not create an attorney-client relationship. You are solely responsible for any actions you take or 
          decisions you make based on the information provided. Always consult with a qualified legal professional before signing any binding agreement.
        </p>
      </div>
    </footer>
  );
};
